.\" Copyright (C) 2010-13 RouterKeygen
.\" Author: Rui Araújo <ruka.araujo@gmail.com>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License 
.\" along with this; if not write to the Free Software Foundation, Inc.
.\" 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
.TH RouterKeygen 1 "Aug 29, 2013"
.SH NAME
routerkeygen \- RouterKeygen
.SH SYNOPSIS
.B routerkeygen
.RI [ OPTIONS ]
.SH DESCRIPTION
Router Keygen generate default WPA/WEP keys for the following router:

  # Thomson based routers ( this includes Thomson, SpeedTouch, Orange, Infinitum, BBox, DMax, BigPond, O2Wireless, Otenet, Cyta , TN_private, Blink )
  # DLink ( only some models )
  # Pirelli Discus
  # Eircom
  # Verizon FiOS ( only some routers supported)
  # Alice AGPF
  # FASTWEB Pirelli and Telsey
  # Huawei (some InfinitumXXXX)
  # Wlan_XXXX or Jazztel_XXXX
  # Wlan_XX ( only some are supported)
  # Ono ( P1XXXXXX0000X )
  # WlanXXXXXX, YacomXXXXXX and WifiXXXXXX
  # Sky V1 routers
  # Clubinternet.box v1 and v2 ( TECOM-AH4XXXX )
  # InfostradaWifi
  # CONN-X
  # Megared
  # EasyBox, Arcor and Vodafone
  # PBS (Austria)
  # MAXCOM
  # PTV
  # TeleTu/Tele2
  # Axtel, Axtel-xtremo
  # Intercable
  # OTE
  # Cabovisao Sagem
  # Alice in Germany
  # Speedport

.SH OPTIONS
If any option is specified, except for
.BI \-\-no-gui
, the program will terminate after processing the command.
.TP
.B \-\-ssid|\-s  \fInetwork_name\fR
Specifies a network to test if it is possible to generate a default key. It may be necessary to specify the MAC address for a correct identification.
.TP
.B \-\-mac|\-m \fImac_address\fR
Specifies the MAC address of a router to test if it is possible to generate a default key.It may be necessary to specify the network name ( see above ) for a correct identification.
.TP
.B \-\-help|\-h
Outputs help.
.TP
.B \-\-version|\-v
Outputs version information and exits.
.TP
.B \-\-no-gui
Executes without displaying the main windows, displaying only the system tray indicator. This is an option by the lauch script when the program start automatically after boot-up. 
.SH BUGS
If you find a bug, please report it to exobel@gmail.com
.PP
.SH AUTHOR
This manual page was written by Rui Araújo <ruka.araujo@gmail.com>, for the Debian
GNU/Linux system (but may be used by others).
